import { z } from 'zod';
export const statusSchema=z.enum(['DEMO','IMPORTED','REVIEW_PENDING','VALIDATED','REJECTED']);
export const designSchema=z.enum(['CONTROLLED_HUMAN','OBSERVATIONAL_HUMAN','ANIMAL','IN_VITRO','MECHANISTIC','UNSPECIFIED']);
export const sourceSchema=z.object({id:z.string().min(1),sourceName:z.enum(['IMPPAT','PubChem','ChEMBL','PubMed','Flockhart','Literature','PolyGuard demo']),sourceRecordId:z.string().min(1),sourceUrl:z.string().url().startsWith('https://'),retrievedAt:z.string().datetime(),sourceVersion:z.string().optional(),usageNote:z.string().min(1),importMethod:z.string().min(1),query:z.string().optional(),title:z.string().optional(),authors:z.array(z.string()).default([]),journal:z.string().optional(),publicationYear:z.number().int().optional(),pmid:z.string().regex(/^\d+$/).optional(),doi:z.string().optional(),abstract:z.string().optional(),contentHash:z.string().optional()});
export const scienceNodeSchema=z.object({id:z.string().min(1),label:z.string().min(1),kind:z.enum(['herb','plant_part','phytochemical','target','pathway','drug','evidence','source','simulation']),identifiers:z.record(z.string(),z.string()).default({})});
export const predicateSchema=z.enum(['HERB_CONTAINS_PHYTOCHEMICAL','HERB_HAS_PLANT_PART','PHYTOCHEMICAL_TESTED_AGAINST_TARGET','PHYTOCHEMICAL_INHIBITS_TARGET','PHYTOCHEMICAL_INDUCES_TARGET','DRUG_IS_SUBSTRATE_OF','DRUG_INHIBITS','DRUG_INDUCES','EVIDENCE_SUPPORTS_RELATIONSHIP','SOURCE_PROVIDES_EVIDENCE','HERB_DRUG_INTERACTION','COMPOUND_DRUG_OBSERVATION','CHEMICAL_IDENTITY','LITERATURE_CANDIDATE']);
export const recordSchema=z.object({id:z.string().min(1),source:sourceSchema,subject:scienceNodeSchema,predicate:predicateSchema,object:scienceNodeSchema,status:statusSchema.default('REVIEW_PENDING'),studyDesign:designSchema.default('UNSPECIFIED'),evidenceGrade:z.enum(['A','B','C','D','E','U']).default('U'),summary:z.string().min(1),limitations:z.string().min(1),plantPart:z.string().optional(),assay:z.object({assayId:z.string(),targetId:z.string(),targetName:z.string(),assayType:z.string().optional(),standardType:z.string().optional(),standardRelation:z.string().optional(),standardValue:z.number().finite().nullable().optional(),standardUnits:z.string().optional(),pChemblValue:z.number().finite().nullable().optional(),documentId:z.string().optional(),confidenceScore:z.number().optional()}).optional(),chemical:z.record(z.string(),z.union([z.string(),z.number(),z.array(z.string())])).optional(),interaction:z.object({herbId:z.string(),drugId:z.string(),potentialConcern:z.enum(['LOW','MODERATE','HIGH','UNKNOWN']).default('UNKNOWN'),outcome:z.enum(['SIGNAL','NO_DETECTED_EFFECT','UNCERTAIN']).default('UNCERTAIN'),preparation:z.string().min(1)}).optional(),timingRelevant:z.boolean().default(false),timingEvidence:z.string().optional(),timingSource:z.string().url().optional(),timingNotes:z.string().optional(),recommendedIntervalFromSource:z.string().optional(),review:z.object({reviewedBy:z.string().min(2),reviewedAt:z.string().datetime(),notes:z.string().min(10)}).optional(),revision:z.number().int().nonnegative().default(0)}).superRefine((r,c)=>{
 if(r.status==='DEMO'&&r.source.sourceName!=='PolyGuard demo')c.addIssue({code:'custom',message:'Demo requires demo provenance'});
 if(r.status==='VALIDATED'&&(!r.review||r.source.sourceName==='PolyGuard demo'))c.addIssue({code:'custom',message:'Validation requires human review and non-demo provenance'});
 if(r.timingRelevant&&(!r.timingEvidence||!r.timingSource||r.status!=='VALIDATED'))c.addIssue({code:'custom',message:'Timing requires validated explicit evidence'});
 if(!r.timingRelevant&&r.recommendedIntervalFromSource)c.addIssue({code:'custom',message:'No timing interval without timing evidence'});
});
export type ScientificRecord=z.infer<typeof recordSchema>;
export type SourceRecord=z.infer<typeof sourceSchema>;
export type ReviewStatus=z.infer<typeof statusSchema>;
export type StudyDesign=z.infer<typeof designSchema>;
export function gradeFromDesign(design:StudyDesign){return ({CONTROLLED_HUMAN:'A',OBSERVATIONAL_HUMAN:'B',ANIMAL:'C',IN_VITRO:'D',MECHANISTIC:'E',UNSPECIFIED:'U'} as const)[design];}
export const reviewSchema=z.object({id:z.string(),revision:z.number().int().nonnegative(),status:z.enum(['VALIDATED','REJECTED','REVIEW_PENDING']),reviewedBy:z.string().trim().min(2).max(120),notes:z.string().trim().min(10).max(4000),studyDesign:designSchema,sourceConfirmed:z.boolean(),outcome:z.enum(['SIGNAL','NO_DETECTED_EFFECT','UNCERTAIN']).optional(),potentialConcern:z.enum(['LOW','MODERATE','HIGH','UNKNOWN']).optional()});
export function reviewRecord(record:ScientificRecord,input:unknown,now=new Date().toISOString()):ScientificRecord{
 const decision=reviewSchema.parse(input);
 if(record.id!==decision.id||record.revision!==decision.revision)throw new Error('STALE_REVIEW');
 if(record.status==='DEMO'||record.source.sourceName==='PolyGuard demo')throw new Error('Demo records cannot enter scientific review');
 if(decision.status==='VALIDATED'&&!decision.sourceConfirmed)throw new Error('Confirm source and relationship scope before validation');
 if(decision.status==='VALIDATED'&&record.predicate==='LITERATURE_CANDIDATE')throw new Error('A bibliographic candidate is not a scientific relationship');
 if(decision.status==='VALIDATED'&&record.interaction&&(!decision.outcome||!decision.potentialConcern))throw new Error('Explicit interpretation required');
 return recordSchema.parse({...record,status:decision.status,studyDesign:decision.studyDesign,evidenceGrade:gradeFromDesign(decision.studyDesign),interaction:record.interaction?{...record.interaction,outcome:decision.outcome??record.interaction.outcome,potentialConcern:decision.potentialConcern??record.interaction.potentialConcern}:undefined,revision:record.revision+1,review:{reviewedBy:decision.reviewedBy,reviewedAt:now,notes:decision.notes}});
}
