'use client';
import {useMemo,useState} from 'react';
import dynamic from 'next/dynamic';
import type {Analysis} from '@/types/polyguard';
import {exploreCounterfactuals,type GraphScenario} from '@/lib/counterfactual';
import {Button} from './ui/button';
const EvidenceGraph=dynamic(()=>import('./evidence-graph'),{ssr:false});
export default function CounterfactualExplorer({result}:{result:Analysis}){
 const analysis=useMemo(()=>exploreCounterfactuals(result),[result]);const [view,setView]=useState<GraphScenario|null>(null);
 const scenarios=[...analysis.singles,...analysis.frontier.filter(s=>s.scenario.length>1)];
 return <section className="counterfactual"><h3>Counterfactual Regimen Explorer</h3><div className="demo-banner"><p><strong>{analysis.disclaimer}</strong><br/>Only herb nodes are considered. The current regimen is unchanged. {result.demo?'These scenarios use synthetic demo evidence.':''}</p></div><p>Structural contribution: {analysis.participation.map(p=>`${p.name}: ${p.signals} signals / ${p.edges} evidence edges`).join(' · ')||'No eligible evidence-supported signals.'}</p><p>{analysis.exact?'Exact enumeration':'Bounded enumeration up to three herbs'} · {analysis.enumerated} subsets evaluated. This minimizes excluded graph nodes for a coverage target, not medical risk.</p>{analysis.minimumCover&&<p>Smallest graph-only cover of all detected signals: {analysis.minimumCover.scenario.length} herb node(s). This is a combinatorial result, not a preferred regimen.</p>}<div className="scenario-grid">{scenarios.map(s=><article className="source-card" key={s.id}><span className="eyebrow">GRAPH SCENARIO</span><h3>Exclude {s.names.join(' + ')} from analysis</h3><strong className="scenario-count">{s.signalsBefore} → {s.signalsAfter} signals</strong><p>{s.affectedEdges.length} graph edges affected · Pathways changed: {s.sharedPathwaysChanged.join(', ')||'None'}</p><p>Evidence represented: {Object.entries(s.evidenceStatuses).map(([k,v])=>`${v} ${k}`).join(' · ')}</p><p>Grades affected: {Object.entries(s.evidenceStrengths).map(([k,v])=>`${k}: ${v}`).join(' · ')}</p><Button onClick={()=>setView(s)}>View Graph Change</Button></article>)}</div>{view&&<div className="scenario-preview"><div className="evidence-title"><h3>Graph-only exclusion: {view.names.join(', ')}</h3><button onClick={()=>setView(null)}>Close scenario</button></div><p>Removed edges: {view.affectedEdges.join(', ')}</p><EvidenceGraph result={view.result} selected={null} onSelect={()=>{}}/></div>}</section>;
}
