'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ScientificEvidence} from './scientific-evidence';
import {Button} from './ui/button';
import type {ScientificRecord,StudyDesign} from '@/types/scientific';
function ReviewForm({record:r,onSaved}:{record:ScientificRecord;onSaved:(r:ScientificRecord)=>void}){
 const [reviewer,setReviewer]=useState(''),[notes,setNotes]=useState(''),[design,setDesign]=useState<StudyDesign>(r.studyDesign),[confirmed,setConfirmed]=useState(false),[outcome,setOutcome]=useState(r.interaction?.outcome??'UNCERTAIN'),[concern,setConcern]=useState(r.interaction?.potentialConcern??'UNKNOWN'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(status:string){setBusy(true);setError('');try{const response=await fetch('/api/research',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:r.id,revision:r.revision,status,reviewedBy:reviewer,notes,studyDesign:design,sourceConfirmed:confirmed,outcome,potentialConcern:concern})});const body=await response.json();if(!response.ok)throw new Error(body.error);onSaved(body);}catch(e){setError(e instanceof Error?e.message:'Review failed');}finally{setBusy(false);}}
 return <fieldset className="review-form" disabled={busy}><legend>Human scientific review</legend><label>Reviewer name<input value={reviewer} onChange={e=>setReviewer(e.target.value)} required/></label><label>Study design<select value={design} onChange={e=>setDesign(e.target.value as StudyDesign)}>{['UNSPECIFIED','CONTROLLED_HUMAN','OBSERVATIONAL_HUMAN','ANIMAL','IN_VITRO','MECHANISTIC'].map(x=><option key={x}>{x}</option>)}</select></label>{r.interaction&&<><label>Reviewed observation<select value={outcome} onChange={e=>setOutcome(e.target.value as typeof outcome)}>{['UNCERTAIN','SIGNAL','NO_DETECTED_EFFECT'].map(x=><option key={x}>{x}</option>)}</select></label><label>Potential concern (independent of grade)<select value={concern} onChange={e=>setConcern(e.target.value as typeof concern)}>{['UNKNOWN','LOW','MODERATE','HIGH'].map(x=><option key={x}>{x}</option>)}</select></label></>}<label className="wide">Review notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Explain source support, study limitations, preparation, and applicability."/></label><label className="wide checkbox"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I reviewed the source and confirmed this exact relationship, population, and preparation scope.</label><div className="wide review-actions"><Button disabled={!confirmed||reviewer.trim().length<2||notes.trim().length<10||r.predicate==='LITERATURE_CANDIDATE'} onClick={()=>submit('VALIDATED')}>Validate</Button><Button disabled={reviewer.trim().length<2||notes.trim().length<10} onClick={()=>submit('REJECTED')}>Reject</Button><Button disabled={reviewer.trim().length<2||notes.trim().length<10} onClick={()=>submit('REVIEW_PENDING')}>Needs review</Button></div>{r.predicate==='LITERATURE_CANDIDATE'&&<p className="wide">Bibliographic metadata cannot be validated as an interaction. Review a specific relationship candidate instead.</p>}{error&&<p className="wide error" role="alert">{error}</p>}</fieldset>;
}
function AiExtractButton({record:r}:{record:ScientificRecord}){const [candidate,setCandidate]=useState<unknown>(null);const [busy,setBusy]=useState(false);async function run(){setBusy(true);const response=await fetch('/api/research/ai-extract',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({abstract:r.source.abstract,pmid:r.source.pmid,doi:r.source.doi,title:r.source.title})});setCandidate(await response.json());setBusy(false);}return <div className="ai-curation"><Button disabled={busy} onClick={run}>{busy?'Extracting…':'Optional AI extraction'}</Button><small>Produces AI_EXTRACTED_CANDIDATE only; human review is still required.</small>{candidate !== null && candidate !== undefined ? <pre>{String(JSON.stringify(candidate,null,2))}</pre> : null}</div>}
export default function Curation(){
 const [records,setRecords]=useState<ScientificRecord[]>([]),[filter,setFilter]=useState('REVIEW_PENDING'),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/research').then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);setRecords(b.records);}).catch(e=>setError(e.message));},[]);
 return <main className="research-page"><Link href="/" className="text-link">← Regimen workspace</Link><div className="eyebrow">DATA · PROVENANCE · HUMAN REVIEW</div><h1>Evidence curation queue</h1><div className="demo-banner"><p><strong>LOCAL HACKATHON RESEARCH INTERFACE</strong><br/>This interface has no user authentication. Reviewer names are self-declared. Do not expose this server publicly. Validation records a source review, not clinical validation.</p></div><div className="quality-grid">{['VALIDATED','REVIEW_PENDING','IMPORTED','REJECTED'].map(s=><div key={s}><strong>{records.filter(r=>r.status===s).length}</strong><span>{s.replaceAll('_',' ')}</span></div>)}</div><p>Literature metadata, assay measurements, and interaction findings remain separate. Null-effect findings must not become interaction flags.</p><label className="research-filter">Review state<select value={filter} onChange={e=>setFilter(e.target.value)}>{['ALL','REVIEW_PENDING','IMPORTED','VALIDATED','REJECTED'].map(s=><option key={s}>{s}</option>)}</select></label>{error&&<p role="alert" className="error">{error}</p>}<div className="research-records">{records.filter(r=>filter==='ALL'||r.status===filter).map(r=><article className="source-card" key={`${r.id}:${r.revision}`}><ScientificEvidence record={r}/>{r.status!=='REJECTED'&&<AiExtractButton record={r}/>}<details><summary>Review this record</summary><ReviewForm record={r} onSaved={updated=>setRecords(old=>old.map(x=>x.id===updated.id?updated:x))}/></details></article>)}{!records.filter(r=>filter==='ALL'||r.status===filter).length&&<p className="blank-note">No records in this review state.</p>}</div></main>;
}
