import {readdirSync,readFileSync,writeFileSync} from 'node:fs';
import {recordSchema,type ScientificRecord} from '../types/scientific';
import {candidate,node} from '../lib/importers/common';
import {importRecords} from '../lib/research/repository';
import {db} from '../lib/db';
const imported=readdirSync('data/imported').filter(f=>f.startsWith('pubmed-')).flatMap(f=>JSON.parse(readFileSync(`data/imported/${f}`,'utf8')) as ScientificRecord[]);
const rows:ScientificRecord[]=[];
const source=(pmid:string)=>{const r=imported.find(r=>r.source.pmid===pmid);if(!r)throw new Error(`Import PMID ${pmid} first`);return {...r.source,importMethod:'NCBI EFetch metadata + assistant-prepared candidate summary; human review pending'};};
function pair(pmid:string,herbId:string,herb:string,drugId:string,drug:string,summary:string,outcome:'SIGNAL'|'NO_DETECTED_EFFECT',preparation:string){rows.push(candidate({id:`candidate-${pmid}-${herbId}-${drugId}`,source:source(pmid),subject:node(herbId,herb,'herb'),predicate:'HERB_DRUG_INTERACTION',object:node(drugId,drug,'drug'),summary,limitations:'Candidate interpretation from the cited study, not yet reviewed by a researcher. Findings are limited to the studied preparation, population, and endpoints; do not generalize to an individual.',interaction:{herbId,drugId,potentialConcern:'UNKNOWN',outcome,preparation}}));}
pair('11740713','garlic','Garlic','saquinavir','Saquinavir','A small healthy-volunteer study reported reduced saquinavir exposure during garlic-caplet use. The preparation-specific observation does not identify a proven causal pathway.','SIGNAL','Garlic caplets with the studied Fortovase saquinavir formulation');
pair('15801937','ginger','Ginger','warfarin','Warfarin','The crossover study did not detect a significant effect of its ginger product on warfarin pharmacokinetics or pharmacodynamics. This is a null-effect observation, not a safety guarantee.','NO_DETECTED_EFFECT','Ginger product of known quality used in the cited healthy-volunteer trial');
pair('16883626','ginger','Ginger','nifedipine','Nifedipine','The study reported enhanced inhibition of platelet aggregation with ginger and nifedipine. The measured endpoint is not a quantified clinical bleeding outcome.','SIGNAL','Ginger preparation and nifedipine studied in volunteers and hypertensive participants');
pair('12891227','garlic','Garlic','alprazolam','Alprazolam','The study found no significant change in alprazolam pharmacokinetic parameters after the tested garlic extract.','NO_DETECTED_EFFECT','Garlic extract in the cited 14-day healthy-volunteer study');
pair('12891227','garlic','Garlic','dextromethorphan','Dextromethorphan','The study found no significant change in the urinary dextromethorphan metabolic ratio after the tested garlic extract.','NO_DETECTED_EFFECT','Garlic extract and CYP2D6 probe used in the cited study');
pair('15974642','garlic','Garlic','chlorzoxazone','Chlorzoxazone','The study reported reduced CYP2E1 phenotypic activity with garlic oil, measured using a chlorzoxazone metabolic ratio. It did not establish individual clinical harm.','SIGNAL','Garlic oil; single-timepoint probe ratio in a small elderly-volunteer crossover study');
pair('15974642','garlic','Garlic','caffeine','Caffeine','The tested botanical supplements did not appear to affect CYP1A2 phenotypic activity measured with caffeine. This does not establish general safety.','NO_DETECTED_EFFECT','Garlic oil; caffeine phenotyping in elderly volunteers');
for(const [pmid,id,label,drugId,drug,summary] of [['17468862','pubchem:969516','Curcumin','talinolol','Talinolol','The controlled study reported reduced talinolol exposure during isolated curcumin administration. This cannot be equated with a whole-turmeric product.'],['20393696','glycyrrhizin','Glycyrrhizin','midazolam','Midazolam','The randomized crossover study reported reduced midazolam exposure after glycyrrhizin. This isolated-compound finding cannot be equated with whole licorice.']])rows.push(candidate({id:`candidate-${pmid}-compound-observation`,source:source(pmid),subject:node(id,label,'phytochemical'),predicate:'COMPOUND_DRUG_OBSERVATION',object:node(drugId,drug,'drug'),summary,limitations:'Isolated compound, study-specific formulation and population. No whole-herb interaction or missing mechanism edge is inferred.'}));
for(const [drugId,drug,target] of [['alprazolam','Alprazolam','CYP3A4'],['dextromethorphan','Dextromethorphan','CYP2D6']])rows.push(candidate({id:`candidate-12891227-${drugId}-substrate`,source:source('12891227'),subject:node(drugId,drug,'drug'),predicate:'DRUG_IS_SUBSTRATE_OF',object:node(target,target,'target'),summary:`The study identifies ${drug} as a probe substrate for ${target}.`,limitations:'Probe-substrate identity does not establish a clinically meaningful herb interaction.'}));
rows.push(candidate({id:'candidate-28774812-glabridin-CYP3A4',source:source('28774812'),subject:node('glabridin','Glabridin','phytochemical'),predicate:'PHYTOCHEMICAL_INHIBITS_TARGET',object:node('CYP3A4','CYP3A4','target'),summary:'The laboratory study reports competitive CYP3A4 inhibition by glabridin. No Ki or IC50 is populated from an unavailable numerical assay table.',limitations:'In-vitro result only. No clinical interaction, achievable concentration, or whole-licorice effect is inferred.'}));
try{writeFileSync('data/imported/review-candidates.json',JSON.stringify(rows.map(r=>recordSchema.parse(r)),null,2));console.log(await importRecords(rows));}finally{await db.$disconnect();}
